version: '2'

services:
  app:
    image: 'demo-account:latest'
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: app
    depends_on:
      - db
    networks:
      - app-network
    ports:
      - 8080:8080
    expose:
      - 8080
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    networks:
      - app-network
    ports:
      - 5232:5432
    expose:
      - 5432
networks:
  app-network:
    driver:
      bridge